---
- name: update apt
  command: apt-get update

- name: Install postgresql
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - postgresql 
      - postgresql-10
      - libpq-dev
      - python3.6
      - python3-psycopg2

    state: present
  tags:
    - postgres


- name: Enable passwordless sudo
  lineinfile: dest=/etc/sudoers regexp=^vagrant line="postgres ALL=(ALL) ALL"

- name: Add user to group
  user: name=postgres
        state=present
        groups=sudo 
        append=yes
  tags:
    config_group


- name: 'create user'
  become: yes
  become_user: postgres
  postgresql_user:
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    priv: ALL:SELECT,INSERT,UPDATE,DELETE,CONNEC
#    role_attr_flags: "CREATEDB,NOSUPERUSER"


- name: 'create database'
  become: yes
  become_user: vagrant 
  postgresql_db:
    name: '{{ db_name }}'
    owner: '{{ db_user }}'



#- name: Ensure database is created
#  sudo_user: vagtent
#  postgresql_db: name={{ db_name }}
#             encoding='UTF-8'
#             lc_collate='en_US.UTF-8'
#             lc_ctype='en_US.UTF-8'
#             template='template0'
#             state=present

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db={{ db_name }}
               name={{ db_user }}
               password={{ db_password }}
               priv=ALL
               state=present

- name: Ensure user does not have unnecessary privileges
  sudo_user: vagrant
  postgresql_user: name={{ db_user }}
               role_attr_flags=NOSUPERUSER,NOCREATEDB
               state=p





- name: restart postgres
  service:
    name=postgresql
    state=restarted
